using System.Text;
using Microsoft.IdentityModel.Tokens;

namespace KioskBrains.Server.Domain.Security
{
    internal class JwtAuthOptions
    {
        public const string Issuer = "KioskBrains";

        public const string Audience = "KioskBrains";

        // generated by https://www.grc.com/passwords.htm
        private const string Key = "E9DDCAC3EAFB276178346BBF9F33C26F51B12A11B19B77F11EECF1973861C42B";

        public const int PortalUserLifetimeMinutes = 4 * 60; // 4 hours

        // todo: think about API token invalidation strategy
        public const int AppClientLifetimeDays = 10*365; // 10 years

        public static SymmetricSecurityKey GetSymmetricSecurityKey()
        {
            return new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Key));
        }
    }
}