using Microsoft.EntityFrameworkCore.Migrations;

namespace KioskBrains.Server.Domain.Migrations
{
    public partial class countries : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Afghanistan', N'004', N'AF', N'AFG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Åland Islands', N'248', N'AX', N'ALA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Albania', N'008', N'AL', N'ALB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Algeria', N'012', N'DZ', N'DZA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'American Samoa', N'016', N'AS', N'ASM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Andorra', N'020', N'AD', N'AND');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Angola', N'024', N'AO', N'AGO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Anguilla', N'660', N'AI', N'AIA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Antarctica', N'010', N'AQ', N'ATA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Antigua and Barbuda', N'028', N'AG', N'ATG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Argentina', N'032', N'AR', N'ARG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Armenia', N'051', N'AM', N'ARM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Aruba', N'533', N'AW', N'ABW');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Australia', N'036', N'AU', N'AUS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Austria', N'040', N'AT', N'AUT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Azerbaijan', N'031', N'AZ', N'AZE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bahamas', N'044', N'BS', N'BHS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bahrain', N'048', N'BH', N'BHR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bangladesh', N'050', N'BD', N'BGD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Barbados', N'052', N'BB', N'BRB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Belarus', N'112', N'BY', N'BLR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Belgium', N'056', N'BE', N'BEL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Belize', N'084', N'BZ', N'BLZ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Benin', N'204', N'BJ', N'BEN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bermuda', N'060', N'BM', N'BMU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bhutan', N'064', N'BT', N'BTN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bolivia (Plurinational State of)', N'068', N'BO', N'BOL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bonaire, Sint Eustatius and Saba', N'535', N'BQ', N'BES');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bosnia and Herzegovina', N'070', N'BA', N'BIH');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Botswana', N'072', N'BW', N'BWA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bouvet Island', N'074', N'BV', N'BVT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Brazil', N'076', N'BR', N'BRA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'British Indian Ocean Territory', N'086', N'IO', N'IOT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Brunei Darussalam', N'096', N'BN', N'BRN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Bulgaria', N'100', N'BG', N'BGR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Burkina Faso', N'854', N'BF', N'BFA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Burundi', N'108', N'BI', N'BDI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cambodia', N'116', N'KH', N'KHM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cameroon', N'120', N'CM', N'CMR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Canada', N'124', N'CA', N'CAN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cabo Verde', N'132', N'CV', N'CPV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cayman Islands', N'136', N'KY', N'CYM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Central African Republic', N'140', N'CF', N'CAF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Chad', N'148', N'TD', N'TCD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Chile', N'152', N'CL', N'CHL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'China', N'156', N'CN', N'CHN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Christmas Island', N'162', N'CX', N'CXR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cocos (Keeling) Islands', N'166', N'CC', N'CCK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Colombia', N'170', N'CO', N'COL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Comoros', N'174', N'KM', N'COM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Congo', N'178', N'CG', N'COG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Congo (Democratic Republic of the)', N'180', N'CD', N'COD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cook Islands', N'184', N'CK', N'COK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Costa Rica', N'188', N'CR', N'CRI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Côte d''Ivoire', N'384', N'CI', N'CIV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Croatia', N'191', N'HR', N'HRV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cuba', N'192', N'CU', N'CUB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Curaçao', N'531', N'CW', N'CUW');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Cyprus', N'196', N'CY', N'CYP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Czech Republic', N'203', N'CZ', N'CZE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Denmark', N'208', N'DK', N'DNK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Djibouti', N'262', N'DJ', N'DJI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Dominica', N'212', N'DM', N'DMA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Dominican Republic', N'214', N'DO', N'DOM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Ecuador', N'218', N'EC', N'ECU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Egypt', N'818', N'EG', N'EGY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'El Salvador', N'222', N'SV', N'SLV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Equatorial Guinea', N'226', N'GQ', N'GNQ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Eritrea', N'232', N'ER', N'ERI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Estonia', N'233', N'EE', N'EST');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Ethiopia', N'231', N'ET', N'ETH');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Falkland Islands (Malvinas)', N'238', N'FK', N'FLK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Faroe Islands', N'234', N'FO', N'FRO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Fiji', N'242', N'FJ', N'FJI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Finland', N'246', N'FI', N'FIN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'France', N'250', N'FR', N'FRA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'French Guiana', N'254', N'GF', N'GUF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'French Polynesia', N'258', N'PF', N'PYF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'French Southern Territories', N'260', N'TF', N'ATF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Gabon', N'266', N'GA', N'GAB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Gambia', N'270', N'GM', N'GMB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Georgia', N'268', N'GE', N'GEO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Germany', N'276', N'DE', N'DEU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Ghana', N'288', N'GH', N'GHA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Gibraltar', N'292', N'GI', N'GIB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Greece', N'300', N'GR', N'GRC');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Greenland', N'304', N'GL', N'GRL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Grenada', N'308', N'GD', N'GRD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guadeloupe', N'312', N'GP', N'GLP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guam', N'316', N'GU', N'GUM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guatemala', N'320', N'GT', N'GTM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guernsey', N'831', N'GG', N'GGY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guinea', N'324', N'GN', N'GIN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guinea-Bissau', N'624', N'GW', N'GNB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Guyana', N'328', N'GY', N'GUY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Haiti', N'332', N'HT', N'HTI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Heard Island and McDonald Islands', N'334', N'HM', N'HMD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Holy See', N'336', N'VA', N'VAT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Honduras', N'340', N'HN', N'HND');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Hong Kong', N'344', N'HK', N'HKG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Hungary', N'348', N'HU', N'HUN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Iceland', N'352', N'IS', N'ISL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'India', N'356', N'IN', N'IND');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Indonesia', N'360', N'ID', N'IDN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Iran (Islamic Republic of)', N'364', N'IR', N'IRN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Iraq', N'368', N'IQ', N'IRQ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Ireland', N'372', N'IE', N'IRL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Isle of Man', N'833', N'IM', N'IMN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Israel', N'376', N'IL', N'ISR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Italy', N'380', N'IT', N'ITA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Jamaica', N'388', N'JM', N'JAM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Japan', N'392', N'JP', N'JPN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Jersey', N'832', N'JE', N'JEY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Jordan', N'400', N'JO', N'JOR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Kazakhstan', N'398', N'KZ', N'KAZ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Kenya', N'404', N'KE', N'KEN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Kiribati', N'296', N'KI', N'KIR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Korea (Democratic People''s Republic of)', N'408', N'KP', N'PRK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Korea (Republic of)', N'410', N'KR', N'KOR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Kuwait', N'414', N'KW', N'KWT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Kyrgyzstan', N'417', N'KG', N'KGZ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Lao People''s Democratic Republic', N'418', N'LA', N'LAO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Latvia', N'428', N'LV', N'LVA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Lebanon', N'422', N'LB', N'LBN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Lesotho', N'426', N'LS', N'LSO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Liberia', N'430', N'LR', N'LBR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Libya', N'434', N'LY', N'LBY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Liechtenstein', N'438', N'LI', N'LIE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Lithuania', N'440', N'LT', N'LTU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Luxembourg', N'442', N'LU', N'LUX');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Macao', N'446', N'MO', N'MAC');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Macedonia (the former Yugoslav Republic of)', N'807', N'MK', N'MKD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Madagascar', N'450', N'MG', N'MDG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Malawi', N'454', N'MW', N'MWI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Malaysia', N'458', N'MY', N'MYS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Maldives', N'462', N'MV', N'MDV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mali', N'466', N'ML', N'MLI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Malta', N'470', N'MT', N'MLT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Marshall Islands', N'584', N'MH', N'MHL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Martinique', N'474', N'MQ', N'MTQ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mauritania', N'478', N'MR', N'MRT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mauritius', N'480', N'MU', N'MUS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mayotte', N'175', N'YT', N'MYT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mexico', N'484', N'MX', N'MEX');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Micronesia (Federated States of)', N'583', N'FM', N'FSM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Moldova (Republic of)', N'498', N'MD', N'MDA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Monaco', N'492', N'MC', N'MCO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mongolia', N'496', N'MN', N'MNG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Montenegro', N'499', N'ME', N'MNE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Montserrat', N'500', N'MS', N'MSR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Morocco', N'504', N'MA', N'MAR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Mozambique', N'508', N'MZ', N'MOZ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Myanmar', N'104', N'MM', N'MMR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Namibia', N'516', N'NA', N'NAM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Nauru', N'520', N'NR', N'NRU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Nepal', N'524', N'NP', N'NPL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Netherlands', N'528', N'NL', N'NLD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'New Caledonia', N'540', N'NC', N'NCL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'New Zealand', N'554', N'NZ', N'NZL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Nicaragua', N'558', N'NI', N'NIC');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Niger', N'562', N'NE', N'NER');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Nigeria', N'566', N'NG', N'NGA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Niue', N'570', N'NU', N'NIU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Norfolk Island', N'574', N'NF', N'NFK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Northern Mariana Islands', N'580', N'MP', N'MNP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Norway', N'578', N'NO', N'NOR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Oman', N'512', N'OM', N'OMN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Pakistan', N'586', N'PK', N'PAK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Palau', N'585', N'PW', N'PLW');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Palestine, State of', N'275', N'PS', N'PSE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Panama', N'591', N'PA', N'PAN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Papua New Guinea', N'598', N'PG', N'PNG');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Paraguay', N'600', N'PY', N'PRY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Peru', N'604', N'PE', N'PER');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Philippines', N'608', N'PH', N'PHL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Pitcairn', N'612', N'PN', N'PCN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Poland', N'616', N'PL', N'POL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Portugal', N'620', N'PT', N'PRT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Puerto Rico', N'630', N'PR', N'PRI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Qatar', N'634', N'QA', N'QAT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Réunion', N'638', N'RE', N'REU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Romania', N'642', N'RO', N'ROU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Russian Federation', N'643', N'RU', N'RUS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Rwanda', N'646', N'RW', N'RWA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Barthélemy', N'652', N'BL', N'BLM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Helena, Ascension and Tristan da Cunha', N'654', N'SH', N'SHN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Kitts and Nevis', N'659', N'KN', N'KNA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Lucia', N'662', N'LC', N'LCA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Martin (French part)', N'663', N'MF', N'MAF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Pierre and Miquelon', N'666', N'PM', N'SPM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saint Vincent and the Grenadines', N'670', N'VC', N'VCT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Samoa', N'882', N'WS', N'WSM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'San Marino', N'674', N'SM', N'SMR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sao Tome and Principe', N'678', N'ST', N'STP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Saudi Arabia', N'682', N'SA', N'SAU');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Senegal', N'686', N'SN', N'SEN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Serbia', N'688', N'RS', N'SRB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Seychelles', N'690', N'SC', N'SYC');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sierra Leone', N'694', N'SL', N'SLE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Singapore', N'702', N'SG', N'SGP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sint Maarten (Dutch part)', N'534', N'SX', N'SXM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Slovakia', N'703', N'SK', N'SVK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Slovenia', N'705', N'SI', N'SVN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Solomon Islands', N'090', N'SB', N'SLB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Somalia', N'706', N'SO', N'SOM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'South Africa', N'710', N'ZA', N'ZAF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'South Georgia and the South Sandwich Islands', N'239', N'GS', N'SGS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'South Sudan', N'728', N'SS', N'SSD');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Spain', N'724', N'ES', N'ESP');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sri Lanka', N'144', N'LK', N'LKA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sudan', N'729', N'SD', N'SDN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Suriname', N'740', N'SR', N'SUR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Svalbard and Jan Mayen', N'744', N'SJ', N'SJM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Swaziland', N'748', N'SZ', N'SWZ');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Sweden', N'752', N'SE', N'SWE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Switzerland', N'756', N'CH', N'CHE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Syrian Arab Republic', N'760', N'SY', N'SYR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Taiwan, Province of China', N'158', N'TW', N'TWN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tajikistan', N'762', N'TJ', N'TJK');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tanzania, United Republic of', N'834', N'TZ', N'TZA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Thailand', N'764', N'TH', N'THA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Timor-Leste', N'626', N'TL', N'TLS');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Togo', N'768', N'TG', N'TGO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tokelau', N'772', N'TK', N'TKL');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tonga', N'776', N'TO', N'TON');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Trinidad and Tobago', N'780', N'TT', N'TTO');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tunisia', N'788', N'TN', N'TUN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Turkey', N'792', N'TR', N'TUR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Turkmenistan', N'795', N'TM', N'TKM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Turks and Caicos Islands', N'796', N'TC', N'TCA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Tuvalu', N'798', N'TV', N'TUV');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Uganda', N'800', N'UG', N'UGA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Ukraine', N'804', N'UA', N'UKR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'United Arab Emirates', N'784', N'AE', N'ARE');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'United Kingdom of Great Britain and Northern Ireland', N'826', N'GB', N'GBR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'United States of America', N'840', N'US', N'USA');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'United States Minor Outlying Islands', N'581', N'UM', N'UMI');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Uruguay', N'858', N'UY', N'URY');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Uzbekistan', N'860', N'UZ', N'UZB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Vanuatu', N'548', N'VU', N'VUT');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Venezuela (Bolivarian Republic of)', N'862', N'VE', N'VEN');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Viet Nam', N'704', N'VN', N'VNM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Virgin Islands (British)', N'092', N'VG', N'VGB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Virgin Islands (U.S.)', N'850', N'VI', N'VIR');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Wallis and Futuna', N'876', N'WF', N'WLF');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Western Sahara', N'732', N'EH', N'ESH');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Yemen', N'887', N'YE', N'YEM');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Zambia', N'894', N'ZM', N'ZMB');
INSERT INTO dbo.Countries(Name, Code, Alpha2, Alpha3) VALUES(N'Zimbabwe', N'716', N'ZW', N'ZWE');");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
