//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskBrains.Server.EK.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KioskBrains.Server.EK.Common.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;carType&quot;:1,&quot;manufacturers&quot;:[{&quot;id&quot;:1505,&quot;name&quot;:&quot;ACURA&quot;,&quot;description&quot;:&quot;Автомобили Акура
        ///INTEGRA
        ///LEGEND
        ///MDX
        ///NSX
        ///RDX
        ///RL
        ///RSX
        ///TL
        ///TSX
        ///CL
        ///Acura -это момент американской истины. На дорогах будешь обращать внимание за пристольный вид и аккуратностью в движении.&quot;,&quot;carModels&quot;:[{&quot;tecDocType&quot;:1,&quot;id&quot;:4403,&quot;name&quot;:&quot;INTEGRA&quot;},{&quot;tecDocType&quot;:1,&quot;id&quot;:4404,&quot;name&quot;:&quot;LEGEND&quot;},{&quot;tecDocType&quot;:1,&quot;id&quot;:6092,&quot;name&quot;:&quot;MDX&quot;},{&quot;tecDocType&quot;:1,&quot;id&quot;:4409,&quot;name&quot;:&quot;NSX&quot;},{&quot;tecDocType&quot;:1,&quot;id&quot;:10307,&quot;name&quot;:&quot;RDX&quot;},{&quot;tecDocType&quot;:1,&quot;id&quot;:612 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarModelTreeJson {
            get {
                return ResourceManager.GetString("CarModelTreeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;categoryId&quot;:&quot;620&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Легковые и микроавтобусы&quot;},&quot;children&quot;:[{&quot;categoryId&quot;:&quot;50821&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Двигун і деталі&quot;},&quot;children&quot;:[{&quot;categoryId&quot;:&quot;50823&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Блок двигуна&quot;},&quot;children&quot;:[{&quot;categoryId&quot;:&quot;50825&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Блок двигуна&quot;},&quot;children&quot;:null},{&quot;categoryId&quot;:&quot;50828&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Вкладиші&quot;},&quot;children&quot;:null},{&quot;categoryId&quot;:&quot;256143&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Датчик положення колінвала&quot;},&quot;children&quot;:null},{&quot;categoryId&quot;:&quot;50831&quot;,&quot;name&quot;:{&quot;ru&quot;:&quot;Колінвал&quot;},&quot;children&quot;:null},{&quot;categoryId&quot;:&quot;50829&quot;,&quot;name&quot;:{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EuropeCategoriesJson {
            get {
                return ResourceManager.GetString("EuropeCategoriesJson", resourceCulture);
            }
        }
    }
}
